Repository 09abhishek/krishna-book-seller-app, pull requests merged in 2022-11, with the labels that each got.

#10 Added users crud apis along with minor bug fixes
  src/app.js
  src/config/db.config.js
  src/config/logger.js
  src/config/morgan.js
  src/config/roles.js
  src/config/tokens.js
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/routes/v1/user.route.js
  src/services/user.service.js
  src/validations/book.validation.js
  src/validations/publication.validation.js
  src/validations/user.validation.js
Labels: enhancement

#19 fixed change quantity issue
  frontend/src/app/app.serveice.ts
  frontend/src/app/book-management/manage-item-list/manage-item-list.component.ts
  frontend/src/app/book-management/manage-item-update/manage-item-update.component.scss
  frontend/src/app/book-management/manage-item-update/manage-item-update.component.ts
  frontend/src/app/book-management/manage-publication-list/manage-publication-list.component.ts
  frontend/src/app/book-management/manage-publication-update/manage-publication-update.component.html
  frontend/src/app/book-management/manage-publication-update/manage-publication-update.component.scss
  frontend/src/app/book-management/manage-publication-update/manage-publication-update.component.ts
  frontend/src/app/book-management/manage-quantity/manage-quantity.component.ts
  frontend/src/app/invoice/invoice/invoice-print.service.ts
  frontend/src/app/invoice/invoice/invoice.component.html
  frontend/src/app/invoice/invoice/invoice.component.ts
  frontend/src/app/invoice/invoice/padf.txt
  frontend/src/app/invoice/search-invoice/search-invoice.component.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/header/header.component.ts
  frontend/src/app/user-management/add-user/add-user.component.html
  frontend/src/app/user-management/add-user/add-user.component.scss
  frontend/src/app/user-management/add-user/add-user.component.ts
  frontend/src/app/user-management/user.module.ts
  frontend/src/app/user-management/user.routing.ts
  frontend/src/app/user-management/user.service.ts
  frontend/src/app/user-management/view-profile/view-profile.component.html
  frontend/src/app/user-management/view-profile/view-profile.component.scss
  frontend/src/app/user-management/view-profile/view-profile.component.spec.ts
  frontend/src/app/user-management/view-profile/view-profile.component.ts
  yarn.lock
Labels: enhancement

#20 worked on invoice page
  frontend/src/app/invoice/invoice/invoice.component.html
  frontend/src/app/invoice/invoice/invoice.component.ts
Labels: enhancement

#21 added invoice print and download icon at invoice page
  frontend/src/app/invoice/invoice/invoice-print.service.ts
  frontend/src/app/invoice/invoice/invoice.component.html
  frontend/src/app/invoice/invoice/invoice.component.scss
  frontend/src/app/invoice/invoice/invoice.component.ts
  frontend/src/app/invoice/search-invoice/search-invoice.component.html
  frontend/src/app/invoice/search-invoice/search-invoice.component.ts
  frontend/src/app/report/component/collection-report/collection-report.component.ts
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.html
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.ts
  frontend/src/app/user-management/add-user/add-user.component.html
  frontend/src/app/user-management/add-user/add-user.component.ts
Labels: enhancement

#22 Kbs frontend UI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/auth/login/login.component.scss
  frontend/src/app/book-management/manage-item-update/manage-item-update.component.ts
  frontend/src/app/book-management/manage-publication-list/manage-publication-list.component.html
  frontend/src/app/book-management/manage-quantity/manage-quantity.component.html
  frontend/src/app/book-management/manage-quantity/manage-quantity.component.ts
  frontend/src/app/invoice/invoice/invoice.component.html
  frontend/src/app/invoice/invoice/invoice.component.scss
  frontend/src/app/invoice/invoice/invoice.component.ts
  frontend/src/app/invoice/search-invoice/search-invoice.component.html
  frontend/src/app/invoice/search-invoice/search-invoice.component.ts
  frontend/src/app/report/component/all-book-list/all-book-list.component.html
  frontend/src/app/report/component/all-book-list/all-book-list.component.scss
  frontend/src/app/report/component/all-book-list/all-book-list.component.ts
  frontend/src/app/report/component/book-stock-report/book-stock-report.component.html
  frontend/src/app/report/component/book-stock-report/book-stock-report.component.scss
  frontend/src/app/report/component/collection-report/collection-report.component.html
  frontend/src/app/report/component/collection-report/collection-report.component.scss
  frontend/src/app/report/component/collection-report/collection-report.component.ts
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.html
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.scss
  frontend/src/app/report/component/publication-report/publication-report.component.html
  frontend/src/app/report/component/publication-report/publication-report.component.scss
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/side-bar/side-bar.component.html
  frontend/src/app/user-management/user-list/user-list.component.html
  frontend/src/assets/img/background.jpg
  frontend/src/assets/img/logo.png
  frontend/src/assets/img/menu/add-user.svg
  frontend/src/assets/img/menu/book-stock.svg
  frontend/src/assets/img/menu/daily-collection.svg
  frontend/src/assets/img/menu/invoice.svg
  frontend/src/assets/img/menu/manage-Quantity.svg
  frontend/src/assets/img/menu/manage-book.svg
  frontend/src/assets/img/menu/manage-item.svg
  frontend/src/assets/img/menu/report.svg
  frontend/src/assets/img/menu/user-list.svg
  frontend/src/styles.scss
Labels: enhancement

#25 Kbs frontend changes
  frontend/src/app/auth/login/login.component.scss
  frontend/src/app/auth/login/login.component.ts
  frontend/src/app/book-management/manage-item-list/manage-item-list.component.html
  frontend/src/app/book-management/manage-item-list/manage-item-list.component.ts
  frontend/src/app/book-management/manage-item-update/manage-item-update.component.ts
  frontend/src/app/book-management/manage-publication-update/manage-publication-update.component.ts
  frontend/src/app/book-management/manage-quantity/manage-quantity.component.scss
  frontend/src/app/book-management/manage-quantity/manage-quantity.component.ts
  frontend/src/app/invoice/invoice/invoice.component.ts
  frontend/src/app/invoice/search-invoice/search-invoice.component.scss
  frontend/src/app/invoice/search-invoice/search-invoice.component.ts
  frontend/src/app/providers/interceptor/request.interceptor.ts
  frontend/src/app/report/component/all-book-list/all-book-list.component.html
  frontend/src/app/report/component/all-book-list/all-book-list.component.ts
  frontend/src/app/report/component/book-stock-report/book-stock-report.component.ts
  frontend/src/app/report/component/collection-report/collection-report.component.ts
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.html
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.ts
  frontend/src/app/report/component/publication-report/publication-report.component.ts
  frontend/src/app/shared/components/loader/loader.component.scss
  frontend/src/app/shared/components/side-bar/side-bar.component.html
  frontend/src/app/user-management/add-user/add-user.component.ts
  frontend/src/assets/img/menu/invoice.svg
  frontend/src/styles.scss
Labels: enhancement

#26 Develop
  frontend/src/app/auth/login/login.component.scss
  frontend/src/app/auth/login/login.component.ts
  frontend/src/app/book-management/manage-quantity/manage-quantity.component.scss
  frontend/src/app/invoice/search-invoice/search-invoice.component.scss
  frontend/src/app/shared/components/loader/loader.component.scss
  frontend/src/app/shared/components/side-bar/side-bar.component.html
  frontend/src/app/user-management/add-user/add-user.component.ts
  frontend/src/assets/img/menu/invoice.svg
  frontend/src/styles.scss
Labels: bug, documentation

#28 fixed frontend isssue
  frontend/src/app/book-management/manage-item-list/manage-item-list.component.html
  frontend/src/app/book-management/manage-item-list/manage-item-list.component.ts
  frontend/src/app/book-management/manage-publication-list/manage-publication-list.component.html
  frontend/src/app/invoice/invoice/invoice-print.service.ts
  frontend/src/app/invoice/invoice/invoice.component.html
  frontend/src/app/invoice/invoice/invoice.component.ts
  frontend/src/app/invoice/search-invoice/search-invoice.component.html
  frontend/src/app/invoice/search-invoice/search-invoice.component.scss
  frontend/src/app/invoice/search-invoice/search-invoice.component.ts
  frontend/src/app/providers/guards/auth.guard.ts
  frontend/src/app/report/component/all-book-list/all-book-list.component.html
  frontend/src/app/report/component/all-book-list/all-book-list.component.ts
  frontend/src/app/report/component/book-stock-report/book-stock-report.component.html
  frontend/src/app/report/component/book-stock-report/book-stock-report.component.ts
  frontend/src/app/report/component/collection-report/collection-report.component.html
  frontend/src/app/report/component/collection-report/collection-report.component.ts
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.html
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.ts
  frontend/src/app/report/component/publication-report/publication-report.component.html
  frontend/src/app/report/component/publication-report/publication-report.component.ts
  frontend/src/app/shared/components/header/header.component.html
  frontend/src/app/shared/components/side-bar/side-bar.component.html
  frontend/src/app/shared/components/side-bar/side-bar.component.ts
  frontend/src/app/user-management/add-user/add-user.component.html
  frontend/src/app/user-management/add-user/add-user.component.ts
  frontend/src/app/user-management/user-list/user-list.component.html
  frontend/src/app/user-management/user-list/user-list.component.ts
  frontend/src/styles.scss
Labels: bug, enhancement

#35 added import export page
  frontend/electron/.gitignore
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/app.serveice.ts
  frontend/src/app/book-management/manage-item-list/manage-item-list.component.ts
  frontend/src/app/book-management/manage-item-update/manage-item-update.component.ts
  frontend/src/app/book-management/manage-publication-update/manage-publication-update.component.ts
  frontend/src/app/book-management/manage-quantity/manage-quantity.component.ts
  frontend/src/app/dashboard/dashboard.component.scss
  frontend/src/app/dashboard/dashboard.component.ts
  frontend/src/app/import-export/import-export.component.html
  frontend/src/app/import-export/import-export.component.scss
  frontend/src/app/import-export/import-export.component.spec.ts
  frontend/src/app/import-export/import-export.component.ts
  frontend/src/app/invoice/invoice/invoice.component.ts
  frontend/src/app/invoice/search-invoice/search-invoice.component.ts
  frontend/src/app/providers/guards/auth.guard.ts
  frontend/src/app/report/component/all-book-list/all-book-list.component.ts
  frontend/src/app/report/component/book-stock-report/book-stock-report.component.ts
  frontend/src/app/report/component/collection-report/collection-report.component.ts
  frontend/src/app/report/component/grant-total-report/grant-total-report.component.ts
  frontend/src/app/shared/components/header/header.component.html
  package-lock.json
  package.json
  uploads/1e31969c2c65a3a26c41f6579e081456
  uploads/3a0e60baa2fdf4f620255dd8aa116866
  uploads/d38497e3824199cfd63e5b58849a3f9f
  yarn.lock
Labels: bug, enhancement
